#!/usr/bin/env python
"""
_shreek_

ShREEK command line binary file that uses command line arguments
to find a ShREEKConfig file and invokes a ShREEKExecutor to run it

"""

import sys
import os
import getopt

from ShREEK.ShREEKConfig import ShREEKConfig
from ShREEK.ShREEKExecutor import ShREEKConfigExecutor
from ShREEK.ShREEKException import ShREEKException




commandOptions  = { "--config" : None,
                    "--interval" : 20,
                    "--debug" : False,
                    "--verbose" : False,
                    "--disableMonitoring": False}




validOpts = ['config=',    
             'interval=', 
             'debug', 
             'verbose', 
             'disableMonitoring', 
             ]


try:
    opts, args =  getopt.getopt(sys.argv[1:], "", validOpts)
        
except getopt.GetoptError, ex:
    msg = "Unknown Option: %s" % ex
    sys.exit(1)

for opt, aval in opts:
    if opt in ('--debug', '--verbose', '--disableMonitoring'):
        aval = True
    
    commandOptions[opt] = aval


if commandOptions['--config'] == None:
    msg = "No ShREEK Config file provided:\n"
    msg += "You must provide the --config=<value> option"
    print msg
    sys.exit(1)

if not os.path.exists(commandOptions['--config']):
    msg = "Config file not found:\n"
    msg += "%s\n" % commandOptions['--config']
    msg += "does not exist, must be a valid path"
    print msg
    sys.exit(1)

#  //
# // Import Core plugins
#//
import ShREEK.ControlPoints.CondImpl
import ShREEK.ControlPoints.ActionImpl

config = ShREEKConfig()
try:
    config.loadFromFile(commandOptions['--config'])
except ShREEKException, ex:
    print "An Error occurred when loading the ShREEK Config File:"
    print str(ex)
    sys.exit(1)


executor = ShREEKConfigExecutor(config)
executor.verbose = commandOptions['--verbose']
executor.debug = commandOptions['--debug']
executor.doMonitoring = not commandOptions['--disableMonitoring']
executor.monitorInterval = int(commandOptions['--interval'])

try:
    executor.run()
    sys.exit(executor.exitCode)
except ShREEKException, ex:
    print "An Error occurred when running ShREEK:"
    print str(ex)
    sys.exit(1)
