#!/usr/bin/env python
"""
_MergeSensorError_

Exceptions generated by the MergeSensor

"""

__revision__ = "$Id: KillerExceptions.py,v 1.1 2007/05/04 08:25:20 ckavka Exp $"
__version__ = "$Revision: 1.1 $"
__author__ = "Carlos.Kavka@ts.infn.it"

##############################################################################
# General errors
##############################################################################

class KillException(Exception):
    """ Exception object for general errors in JobKiller component"""

    def __init__(self, value):
        self.value = value

    def __str__(self):
        return repr(self.value)

##############################################################################
# Non valid datatiers
##############################################################################

class InvalidJobException(Exception):
    """ Exception object for invalid job"""

    def __init__(self, value):
        self.value = value

    def __str__(self):
        return repr(self.value)

##############################################################################
# Job not yet submitted
##############################################################################

class JobNotSubmittedException(Exception):
    """ Exception object for job not submitted"""

    def __init__(self, value):
        self.value = value

    def __str__(self):
        return repr(self.value)


