./upgrageFile.sh CreatorPluginConfig.xml
./upgrageFile.sh env_mytestarea.sh
./upgrageFile.sh RepackerConfig.xml
./upgrageFile.sh prodagent_init.sh
./upgrageFile.sh prodagent_install.sh
./upgrageFile.sh prodagent_mysql_install.sh
./upgrageFile.sh prodagent_rpm_install.sh
./upgrageFile.sh prodagent_start.sh
./upgrageFile.sh SubmitterPluginConfig.xml
